apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: citizen-portal
type: Opaque
stringData:
  PORT: "5000"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "citizen_portal"
  DB_USER: "postgres"
  DB_PASSWORD: "postgres"
  JWT_SECRET: "desc_super_secret_key"
