apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: citizen-portal
type: Opaque
stringData:
  POSTGRES_DB: citizen_portal
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres